spring.application.name=RolesUsuarios
spring.datasource.url=jdbc:mysql://localhost:3306/rolusuario
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=clave-super-secreta-larga-que-nadie-debe-saber-1234567890-abcdefgh
jwt.expiration=3600000